spring.application.name=AIDiaCar
# ????????? JWT
jwt.secret=MySuperSecretKeyForJwtTokenGenerationThatIsLongEnough1234567890
# ????? ????? ?????? ? ????????????? (1 ??? = 3600000)
jwt.expiration=3600000

# ????????? ???? ??????
spring.datasource.url=jdbc:postgresql://localhost:5432/DBAIDiaCar
spring.datasource.username=postgres
spring.datasource.password=1234567890
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
# ???? ? ???????? ?????????? ? ?????????
manuals.root.path=../AIModel/DataPDF

# ???? ??? ???????? ????? ????????
manuals.upload.path=uploads/manuals

# ???? ? ???????? ?????? Tesseract
tesseract.datapath=src/main/resources/tessdata

# ???? ??? ?????????? ??????????????? ???????????
manuals.images.path=uploads/manual-images

# ???????????? ?????? ???????????? ????? (MB)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

file.upload-dir=uploads
spring.web.resources.static-locations=classpath:/static/,file:uploads/

session.images.path=./session-images
# Время жизни неактивной сессии в днях
session.expiration.days=7